# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_foto'),
        ('clientes', '0003_auto_20170625_1625'),
    ]

    operations = [
    ]
